### ISSUE TITLE
apt autoremove

### ISSUE THREAD

**Issue by ahnooie** [robertdebock/ansible-role-update#4]
# apt autoremove

It might be nice to set the autoremove parameter for apt.  http://docs.ansible.com/ansible/latest/apt_module.html

On Ubuntu unless you run apt autoremove periodically the kernel updates will eventually fill up the /boot partition and you'll run out of space.  I'm not sure if it's an issue with other distributions.

**Comment by robertdebock** [comment]
Very useful addition, I'll build it in.

For yum/dnf systems, a system setting ensures a certain amount of kernels is kept, so not applicable. For zypper, pacman and apk systems, I'm not sure.

**Comment by robertdebock** [comment]
Should be solved with the latest merge. @ahnooie can you verify if this works for you? (Tests look good.)

**Comment by ahnooie** [comment]
After testing I found autoremove does not run when combined with update, separated the two in PR #6

**Comment by robertdebock** [comment]
Okay, all build have passed. Please verify again and let me know if this addresses your issue.

Thanks again @ahnooie !

**Comment by ahnooie** [comment]
This works, thanks!
